server.port=${ROOMS_API_PORT:8081}
rooms.api-key=${ROOMS_API_KEY:local-key}

# must be set for the swagger UI to be available
springdoc.api-docs.enabled=true
# this is where Swagger will look for the API definition.
springdoc.swagger-ui.urls[0].name = Rooms API
springdoc.swagger-ui.urls[0].url = /docs/rooms-api-openapi.yml
springdoc.swagger-ui.urls[1].name = Switches API
springdoc.swagger-ui.urls[1].url = /docs/switches-api-openapi.yml