version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "1884:1883"
      - "9001:9001"

  subscriber:
    build:
      context: ..
      dockerfile: src/subscriber/Dockerfile
    depends_on:
      - mosquitto
