version: '3.8'

services:

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"

  mongodb:
    image: mongo:8
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  subscriber:
    build:
      context: ../src/subscriber
      dockerfile: Dockerfile
    container_name: subscriber
    depends_on:
      mongodb:
        condition: service_started
      mosquitto:
        condition: service_started
    environment:
      MQTT_BROKER_URL: ${MQTT_BROKER_URL}
      MQTT_CLIENT_ID: ${MQTT_CLIENT_ID}
      MQTT_TOPIC: ${MQTT_TOPIC}
    restart: unless-stopped

volumes:
  mongo_data:
