mqtt.broker-url=tcp://localhost:1883
mqtt.client-id=JavaSubscriberDev
mqtt.topic=#

spring.data.mongodb.uri=mongodb://localhost:27017
spring.data.mongodb.database=Sensores
mongodb.collection.habitaciones=Habitaciones
mongodb.collection.mediciones=Mediciones