server.port=${SUBSCRIBER_API_PORT:8082}
rooms.swagger-ui.origin=http://localhost:${ROOMS_API_PORT:8080}

mqtt.broker-url=${MQTT_BROKER_URL}
mqtt.client-id=${MQTT_CLIENT_ID}
mqtt.topic=${MQTT_TOPIC}

spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=${MONGODB_DATABASE}

mongodb.collection.habitaciones=${MONGODB_COLLECTION_HABITACIONES}
mongodb.collection.mediciones=${MONGODB_COLLECTION_MEDICIONES}