name: Build & Test
run-name: New changes pushed by @${{ github.actor }} 🚀
on:
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Development
    env:
      MQTT_BROKER_URL: ${{ vars.MQTT_BROKER_URL }}
      MQTT_CLIENT_ID: ${{ vars.MQTT_CLIENT_ID }}
      MQTT_TOPIC: ${{ vars.MQTT_TOPIC }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '25'
          cache: maven

      - name: Build project
        run: mvn -B -DskipTests package

      - name: Upload compiled Maven targets
        uses: actions/upload-artifact@v4
        with:
          name: maven-targets
          path: '**/target/**'
          retention-days: 1

  test:
    needs: build
    runs-on: ubuntu-latest
    environment: Development
    env:
      MQTT_BROKER_URL: ${{ vars.MQTT_BROKER_URL }}
      MQTT_CLIENT_ID: ${{ vars.MQTT_CLIENT_ID }}
      MQTT_TOPIC: ${{ vars.MQTT_TOPIC }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '25'
          cache: maven

      - name: Download compiled Maven targets
        uses: actions/download-artifact@v4
        with:
          name: maven-targets

      - name: Run unit tests
        run: mvn -B test
